"use client";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import { usePathname } from "next/navigation";

const font = Poppins({
  weight: "400",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html
      className="lg:px-[60px] px-5 lg:overflow-x-clip overflow-x-hidden "
      lang="en"
    >
      <body className={font.className}>
        <div className="pb-[7rem]">
          {!pathname.includes("account") && <Topbar currentRoute={pathname} />}
        </div>
        {children}
      </body>
    </html>
  );
}
